"""Export generated content to various formats."""
import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional


def _now_str() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def export_txt(content_map: Dict[str, str], project_title: str,
               output_dir: str) -> str:
    filename = f"{_sanitize(project_title)}_{_now_str()}.txt"
    path = Path(output_dir) / filename
    lines = [
        f"AI YouTube Studio Export",
        f"Project: {project_title}",
        f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}",
        "=" * 60,
        "",
    ]
    for key, text in content_map.items():
        if text:
            label = key.replace("_", " ").title()
            lines.append(f"\n{'=' * 60}")
            lines.append(f"  {label}")
            lines.append(f"{'=' * 60}\n")
            lines.append(text)
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def export_markdown(content_map: Dict[str, str], project_title: str,
                    output_dir: str) -> str:
    filename = f"{_sanitize(project_title)}_{_now_str()}.md"
    path = Path(output_dir) / filename
    lines = [
        f"# {project_title}",
        f"*Generated by AI YouTube Studio on {datetime.now().strftime('%B %d, %Y')}*",
        "",
        "---",
        "",
    ]
    for key, text in content_map.items():
        if text:
            label = key.replace("_", " ").title()
            lines.append(f"## {label}")
            lines.append("")
            lines.append(text)
            lines.append("")
            lines.append("---")
            lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def export_json(content_map: Dict[str, str], project_title: str,
                output_dir: str, metadata: Optional[dict] = None) -> str:
    filename = f"{_sanitize(project_title)}_{_now_str()}.json"
    path = Path(output_dir) / filename
    data = {
        "project": project_title,
        "generated_at": datetime.now().isoformat(),
        "metadata": metadata or {},
        "content": content_map,
    }
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def export_html(content_map: Dict[str, str], project_title: str,
                output_dir: str) -> str:
    filename = f"{_sanitize(project_title)}_{_now_str()}.html"
    path = Path(output_dir) / filename

    sections = ""
    for key, text in content_map.items():
        if text:
            label = key.replace("_", " ").title()
            escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            formatted = escaped.replace("\n\n", "</p><p>").replace("\n", "<br>")
            sections += f"""
<section class="section">
  <h2>{label}</h2>
  <div class="content"><p>{formatted}</p></div>
</section>
"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_title} — AI YouTube Studio</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto;
          padding: 40px 20px; background: #f9f9fb; color: #1a1a2e; }}
  h1 {{ color: #7C3AED; border-bottom: 3px solid #7C3AED; padding-bottom: 10px; }}
  .meta {{ color: #6060aa; font-size: 14px; margin-bottom: 30px; }}
  .section {{ background: white; border-radius: 12px; padding: 24px;
              margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
  h2 {{ color: #4F46E5; margin-top: 0; font-size: 18px; }}
  .content {{ line-height: 1.7; white-space: pre-wrap; }}
  p {{ margin: 0 0 12px; }}
</style>
</head>
<body>
<h1>{project_title}</h1>
<p class="meta">Generated by AI YouTube Studio · {datetime.now().strftime('%B %d, %Y')}</p>
{sections}
</body>
</html>"""
    path.write_text(html, encoding="utf-8")
    return str(path)


def export_docx(content_map: Dict[str, str], project_title: str,
                output_dir: str) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()
    title_p = doc.add_heading(project_title, level=0)
    title_p.runs[0].font.color.rgb = RGBColor(0x7C, 0x3A, 0xED)

    doc.add_paragraph(
        f"Generated by AI YouTube Studio · {datetime.now().strftime('%B %d, %Y')}"
    ).runs[0].font.color.rgb = RGBColor(0x90, 0x90, 0xBB)

    doc.add_page_break()

    for key, text in content_map.items():
        if text:
            label = key.replace("_", " ").title()
            h = doc.add_heading(label, level=1)
            h.runs[0].font.color.rgb = RGBColor(0x4F, 0x46, 0xE5)
            doc.add_paragraph(text)
            doc.add_paragraph("")

    filename = f"{_sanitize(project_title)}_{_now_str()}.docx"
    path = Path(output_dir) / filename
    doc.save(str(path))
    return str(path)


def export_pdf(content_map: Dict[str, str], project_title: str,
               output_dir: str) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
    )

    filename = f"{_sanitize(project_title)}_{_now_str()}.pdf"
    path = Path(output_dir) / filename

    doc = SimpleDocTemplate(str(path), pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm,
                             topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    accent = HexColor("#7C3AED")
    blue = HexColor("#4F46E5")

    title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                  fontSize=22, textColor=accent, spaceAfter=6)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                               fontSize=14, textColor=blue, spaceBefore=16, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                 fontSize=10, leading=16)
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"],
                                 fontSize=10, textColor=HexColor("#9090BB"))

    story = [
        Paragraph(project_title, title_style),
        Paragraph(f"Generated by AI YouTube Studio · "
                  f"{datetime.now().strftime('%B %d, %Y')}", meta_style),
        Spacer(1, 0.4*cm),
        HRFlowable(width="100%", color=accent),
        Spacer(1, 0.4*cm),
    ]

    for key, text in content_map.items():
        if text:
            label = key.replace("_", " ").title()
            story.append(Paragraph(label, h2_style))
            safe = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            for para in safe.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.replace("\n", "<br/>"), body_style))
            story.append(Spacer(1, 0.3*cm))
            story.append(HRFlowable(width="100%", color=HexColor("#E0E0EA"), thickness=0.5))

    doc.build(story)
    return str(path)


def _sanitize(name: str) -> str:
    return "".join(c if c.isalnum() or c in " _-" else "_"
                   for c in name)[:60].strip().replace(" ", "_")
